"""Turn observed usage + findings into a concrete least-privilege recommendation:
the scoped role assignments to keep, the over-broad ones to remove, ready-to-run
``az`` commands, a Bicep snippet, a human-readable report, and a blast-radius
proxy. Pure functions -- runs offline.
"""

from __future__ import annotations

from .diff import covered_operations, diff
from .models import (
    AnalysisResult,
    Finding,
    GrantedRole,
    GrantedTool,
    RecommendedAssignment,
    UsedOperation,
    UsedTool,
)
from .role_catalog import pick_minimal_role
from .tools import analyze_tools


def _scope_weight(scope: str) -> int:
    """Rough 'reach' weight for a scope: broader scope => bigger blast radius.

    A deliberately simple proxy (most-specific check first), labeled as such in
    the report.
    """
    s = scope.lower()
    if "/containers/" in s or "/secrets/" in s or "/blobservices/" in s:
        return 1  # specific sub-resource
    if "/storageaccounts/" in s or "/vaults/" in s:
        return 5  # resource / account
    if "/resourcegroups/" in s:
        return 20  # resource group
    if "/subscriptions/" in s:
        return 100  # subscription
    return 100


def _needed_by_resource(used: list[UsedOperation]) -> dict[tuple[str, str], set[str]]:
    needed: dict[tuple[str, str], set[str]] = {}
    for u in used:
        needed.setdefault((u.service, u.resource_id), set()).add(u.operation)
    return needed


def recommend(
    principal_id: str,
    granted: list[GrantedRole],
    used: list[UsedOperation],
    findings: list[Finding] | None = None,
    granted_tools: list[GrantedTool] | None = None,
    used_tools: list[UsedTool] | None = None,
) -> AnalysisResult:
    if findings is None:
        findings = diff(granted, used)

    # Build the minimal set of scoped assignments that covers actual usage.
    keep: list[RecommendedAssignment] = []
    for (service, resource_id), ops in sorted(_needed_by_resource(used).items()):
        role = pick_minimal_role(service, ops)
        if role is None:
            # Unknown service: flag for manual review rather than guess.
            findings.append(
                Finding(
                    kind="manual_review",
                    severity="low",
                    detail=(
                        f"No catalog role found for service '{service}' covering "
                        f"{sorted(ops)} on '{resource_id}'. Review manually."
                    ),
                    scope=resource_id,
                )
            )
            continue
        keep.append(
            RecommendedAssignment(
                role_name=role.name,
                scope=resource_id,
                covers_operations=sorted(ops),
            )
        )

    # Anything granted that isn't exactly reproduced by a keep is removed.
    keep_key = {(k.role_name, k.scope.rstrip("/").lower()) for k in keep}
    remove = [
        g for g in granted if (g.role_name, g.scope.rstrip("/").lower()) not in keep_key
    ]

    az_cli = _az_commands(principal_id, keep, remove, granted)
    bicep = _bicep(principal_id, keep)

    before = sum(len(covered_operations(g)) * _scope_weight(g.scope) for g in granted)
    after = sum(len(k.covers_operations) * _scope_weight(k.scope) for k in keep)

    result = AnalysisResult(
        principal_id=principal_id,
        findings=findings,
        keep=keep,
        remove=remove,
        az_cli=az_cli,
        bicep=bicep,
        blast_radius_before=before,
        blast_radius_after=after,
    )

    if granted_tools:
        (
            result.tool_findings,
            result.tool_keep,
            result.tool_remove,
            result.tool_guidance,
            result.tool_surface_before,
            result.tool_surface_after,
        ) = analyze_tools(granted_tools, used_tools or [])

    result.report = render_report(result, granted, used)
    return result


def _az_commands(
    principal_id: str,
    keep: list[RecommendedAssignment],
    remove: list[GrantedRole],
    granted: list[GrantedRole],
) -> list[str]:
    cmds: list[str] = []
    granted_keys = {(g.role_name, g.scope.rstrip("/").lower()) for g in granted}
    for k in keep:
        if (k.role_name, k.scope.rstrip("/").lower()) not in granted_keys:
            cmds.append(
                f'az role assignment create --assignee {principal_id} '
                f'--role "{k.role_name}" --scope "{k.scope}"'
            )
    for r in remove:
        cmds.append(
            f'az role assignment delete --assignee {principal_id} '
            f'--role "{r.role_name}" --scope "{r.scope}"'
        )
    return cmds


def _bicep(principal_id: str, keep: list[RecommendedAssignment]) -> str:
    lines = [
        "// Least-privilege role assignments generated by alp.",
        "// Replace <roleDefinitionId> with the GUID for each role name.",
        f"param principalId string = '{principal_id}'",
        "",
    ]
    for i, k in enumerate(keep):
        lines += [
            f"resource ra{i} 'Microsoft.Authorization/roleAssignments@2022-04-01' = {{",
            f"  name: guid(principalId, '{k.role_name}', '{k.scope}')",
            f"  scope: resourceId-for('{k.scope}')  // wire to the target resource",
            "  properties: {",
            "    principalId: principalId",
            "    principalType: 'ServicePrincipal'",
            f"    roleDefinitionId: '<roleDefinitionId for {k.role_name}>'",
            "  }",
            "}",
            "",
        ]
    return "\n".join(lines)


def render_report(
    result: AnalysisResult,
    granted: list[GrantedRole],
    used: list[UsedOperation],
) -> str:
    lines: list[str] = []
    lines.append("=" * 68)
    lines.append("AGENT LEAST-PRIVILEGE ANALYSIS")
    lines.append("=" * 68)
    lines.append(f"Agent principal: {result.principal_id}")
    lines.append("")
    lines.append(f"Granted assignments: {len(granted)}")
    for g in granted:
        lines.append(f"  - {g.role_name}  @  {g.scope}")
    lines.append("")
    lines.append(f"Observed usage: {len(used)} distinct operations")
    for u in used:
        lines.append(f"  - {u.operation:6s} {u.resource_id}  (x{u.count})")
    lines.append("")
    lines.append(f"Findings: {len(result.findings)}")
    for f in result.findings:
        lines.append(f"  [{f.severity.upper():6s}] {f.kind}: {f.detail}")
    lines.append("")
    lines.append("Recommended least-privilege assignments:")
    for k in result.keep:
        lines.append(f"  + {k.role_name}  @  {k.scope}   covers {k.covers_operations}")
    lines.append("")
    lines.append("Remove:")
    for r in result.remove:
        lines.append(f"  - {r.role_name}  @  {r.scope}")
    lines.append("")
    reduction = 0
    if result.blast_radius_before:
        reduction = round(
            100 * (result.blast_radius_before - result.blast_radius_after)
            / result.blast_radius_before
        )
    lines.append(
        f"Blast-radius proxy: {result.blast_radius_before} -> "
        f"{result.blast_radius_after}  ({reduction}% reduction)"
    )
    lines.append("(proxy = permitted operations x scope reach; lower is tighter)")
    lines.append("")
    if result.tool_findings or result.tool_keep or result.tool_remove:
        lines.append("")
        lines.append("-" * 68)
        lines.append("TOOLS / MCP / API PERMISSIONS  (CIEM cannot see this layer)")
        lines.append("-" * 68)
        lines.append(f"Tool findings: {len(result.tool_findings)}")
        for f in result.tool_findings:
            lines.append(f"  [{f.severity.upper():6s}] {f.kind}: {f.detail}")
        if result.tool_remove:
            lines.append("")
            lines.append("Remove tools (never invoked):")
            for t in result.tool_remove:
                lines.append(f"  - {t.kind} '{t.name}'  {t.permissions}")
        if result.tool_keep:
            lines.append("")
            lines.append("Keep (restricted to used scopes):")
            for k in result.tool_keep:
                lines.append(f"  + {k.kind} '{k.name}'  ->  {k.keep_permissions}")
        if result.tool_surface_before:
            tred = round(
                100 * (result.tool_surface_before - result.tool_surface_after)
                / result.tool_surface_before
            )
            lines.append("")
            lines.append(
                f"Tool attack surface: {result.tool_surface_before} -> "
                f"{result.tool_surface_after}  ({tred}% reduction)"
            )
        if result.tool_guidance:
            lines.append("")
            lines.append("Tool changes (agent configuration):")
            for g in result.tool_guidance:
                lines.append(f"  * {g}")

    lines.append("")
    lines.append("Apply RBAC with:")
    for c in result.az_cli:
        lines.append(f"  $ {c}")
    return "\n".join(lines)
